### ISSUE TITLE
서버의 인터넷 연결 확인?

### ISSUE THREAD

**Issue by pp121324** [apexnetwork/SwiftBukkit-Issues#1]
서버가 외부 인터넷으로 통신하는걸 콘솔으로 볼 수 있도록 되어있으면 좋을꺼같아요. 무슨 플러그인이 어디로 뭘 하고있는지 보면서 악성 플러그인 찾을수도 있고..

**Comment by EntryPointKR** [comment]
아직은 모니터링을 어떤 방식으로 할지 모르겠네요

**Comment by swan201** [comment]
이부분은 K-SPAM쪽으로 분류하는게 좋을듯 하네요
