### ISSUE TITLE
아래의 메세지가 뜨면서 서버가 멈춥니다

### ISSUE THREAD

**Issue by rhtrhtwk** [apexnetwork/SwiftBukkit-Issues#2]
---- 스위프트버킷 크래쉬 리포트 ----

설명: 메인 스레드 응답 중지
시간: 1/30/17 3:56 PM

내용: 

서버에 응답이 없습니다!
밑의 내용은 에러 로그가 아닌 당시에 작동하던 스레드의 로그입니다.
밑의 전체 내용을 포함해 https://github.com/apexnetwork/SwiftBukkit-Issues 에 제보해주세요.
버킷 버전: git-Spigot-1.5.2-R1.0-61-gfb828bb (MC: 1.5.2)
현재 스레드 상태:
------------------------------
현재 스레드: File IO Thread
	PID: 68 | Suspended: false | Native: false | State: TIMED_WAITING
	Stack:
		java.lang.Thread.sleep(Native Method)
		net.minecraft.server.v1_5_R3.FileIOThread.b(SourceFile:36)
		net.minecraft.server.v1_5_R3.FileIOThread.run(SourceFile:22)
		java.lang.Thread.run(Unknown Source)
------------------------------
현재 스레드: AWT-Windows
	PID: 62 | Suspended: false | Native: true | State: RUNNABLE
	Stack:
		sun.awt.windows.WToolkit.eventLoop(Native Method)
		sun.awt.windows.WToolkit.run(Unknown Source)
		java.lang.Thread.run(Unknown Source)
------------------------------
현재 스레드: Thread-18
	PID: 41 | Suspended: false | Native: false | State: BLOCKED
	Thread is waiting on monitor(s):
		Locked on:org.bukkit.craftbukkit.v1_5_R3.LoggerOutputStream.flush(LoggerOutputStream.java:27)
		Locked on:java.io.PrintStream.write(Unknown Source)
		Locked on:sun.nio.cs.StreamEncoder.flushBuffer(Unknown Source)
		Locked on:java.io.PrintStream.write(Unknown Source)
		Locked on:java.io.PrintStream.println(Unknown Source)
	Stack:
		java.util.logging.StreamHandler.publish(Unknown Source)
		java.util.logging.ConsoleHandler.publish(Unknown Source)
		java.util.logging.Logger.log(Unknown Source)
		java.util.logging.Logger.doLog(Unknown Source)
		java.util.logging.Logger.logp(Unknown Source)
		org.bukkit.craftbukkit.v1_5_R3.LoggerOutputStream.flush(LoggerOutputStream.java:27)
		java.io.PrintStream.write(Unknown Source)
		sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
		sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
		sun.nio.cs.StreamEncoder.flushBuffer(Unknown Source)
		java.io.OutputStreamWriter.flushBuffer(Unknown Source)
		java.io.PrintStream.write(Unknown Source)
		java.io.PrintStream.print(Unknown Source)
		java.io.PrintStream.println(Unknown Source)
		org.bukkit.craftbukkit.v1_5_R3.command.ColouredConsoleSender.sendMessage(ColouredConsoleSender.java:60)
		net.minecraft.server.v1_5_R3.DedicatedServer.lambda$init$0(DedicatedServer.java:223)
		net.minecraft.server.v1_5_R3.DedicatedServer$$Lambda$7/1974599451.run(Unknown Source)
		java.lang.Thread.run(Unknown Source)
------------------------------
현재 스레드: Timer-2
	PID: 40 | Suspended: false | Native: false | State: TIMED_WAITING
	Stack:
		java.lang.Object.wait(Native Method)
		java.util.TimerThread.mainLoop(Unknown Source)
		java.util.TimerThread.run(Unknown Source)
------------------------------
현재 스레드: Timer-1
	PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
	Stack:
		java.lang.Object.wait(Native Method)
		java.util.TimerThread.mainLoop(Unknown Source)
		java.util.TimerThread.run(Unknown Source)
------------------------------
현재 스레드: Netty IO Thread - 2
	PID: 24 | Suspended: false | Native: false | State: RUNNABLE
	Thread is waiting on monitor(s):
		Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
		Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
		Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	Stack:
		sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
		sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
		sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
		sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
		sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
		sun.nio.ch.SelectorImpl.select(Unknown Source)
		io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:627)
		io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:318)
		io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
		java.lang.Thread.run(Unknown Source)
------------------------------
현재 스레드: Netty IO Thread - 1
	PID: 23 | Suspended: false | Native: true | State: RUNNABLE
	Thread is waiting on monitor(s):
		Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
		Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
		Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	Stack:
		sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
		sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
		sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
		sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
		sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
		sun.nio.ch.SelectorImpl.select(Unknown Source)
		io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:627)
		io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:318)
		io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
		java.lang.Thread.run(Unknown Source)
------------------------------
현재 스레드: Thread-11
	PID: 30 | Suspended: false | Native: false | State: TIMED_WAITING
	Stack:
		java.lang.Thread.sleep(Native Method)
		autosave.AutoBackupThread.run(AutoBackupThread.java:317)
------------------------------
현재 스레드: Thread-10
	PID: 29 | Suspended: false | Native: false | State: TIMED_WAITING
	Stack:
		java.lang.Thread.sleep(Native Method)
		autosave.AutoSaveThread.run(AutoSaveThread.java:93)
------------------------------
현재 스레드: Thread-8
	PID: 27 | Suspended: false | Native: true | State: RUNNABLE
	Thread is waiting on monitor(s):
		Locked on:java.net.PlainSocketImpl.accept(Unknown Source)
	Stack:
		java.net.DualStackPlainSocketImpl.accept0(Native Method)
		java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
		java.net.AbstractPlainSocketImpl.accept(Unknown Source)
		java.net.PlainSocketImpl.accept(Unknown Source)
		java.net.ServerSocket.implAccept(Unknown Source)
		java.net.ServerSocket.accept(Unknown Source)
		com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:114)
------------------------------
현재 스레드: Netty IO Thread - 0
	PID: 22 | Suspended: false | Native: false | State: RUNNABLE
	Thread is waiting on monitor(s):
		Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
		Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
		Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	Stack:
		sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
		sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
		sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
		sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
		sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
		sun.nio.ch.SelectorImpl.select(Unknown Source)
		io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:627)
		io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:318)
		io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
		java.lang.Thread.run(Unknown Source)
------------------------------
현재 스레드: Spigot Metrics Thread
	PID: 21 | Suspended: false | Native: false | State: TIMED_WAITING
	Stack:
		java.lang.Object.wait(Native Method)
		java.util.TimerThread.mainLoop(Unknown Source)
		java.util.TimerThread.run(Unknown Source)
------------------------------
현재 스레드: Spigot Watchdog Thread
	PID: 20 | Suspended: false | Native: false | State: RUNNABLE
	Stack:
		sun.management.ThreadImpl.dumpThreads0(Native Method)
		sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
		org.spigotmc.WatchdogThread.run(WatchdogThread.java:56)
------------------------------
현재 스레드: Command Reader
	PID: 16 | Suspended: false | Native: false | State: RUNNABLE
	Thread is waiting on monitor(s):
		Locked on:org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267)
		Locked on:org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204)
	Stack:
		org.fusesource.jansi.internal.Kernel32._getch(Native Method)
		org.fusesource.jansi.internal.WindowsSupport.readByte(WindowsSupport.java:46)
		org.bukkit.craftbukkit.libs.jline.WindowsTerminal.readByte(WindowsTerminal.java:184)
		org.bukkit.craftbukkit.libs.jline.WindowsTerminal.access$000(WindowsTerminal.java:53)
		org.bukkit.craftbukkit.libs.jline.WindowsTerminal$1.read(WindowsTerminal.java:151)
		java.io.FilterInputStream.read(Unknown Source)
		org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167)
		org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267)
		org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204)
		org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995)
		org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1167)
		net.minecraft.server.v1_5_R3.ThreadCommandReader.run(ThreadCommandReader.java:32)
------------------------------
현재 스레드: DestroyJavaVM
	PID: 15 | Suspended: false | Native: false | State: RUNNABLE
	Stack:
------------------------------
현재 스레드: Server thread
	PID: 14 | Suspended: false | Native: false | State: RUNNABLE
	Thread is waiting on monitor(s):
		Locked on:java.io.BufferedOutputStream.flush(Unknown Source)
		Locked on:java.io.PrintStream.flush(Unknown Source)
		Locked on:sun.nio.cs.StreamEncoder.flush(Unknown Source)
		Locked on:org.bukkit.craftbukkit.v1_5_R3.util.TerminalConsoleHandler.flush(TerminalConsoleHandler.java:23)
	Stack:
		java.io.FileOutputStream.writeBytes(Native Method)
		java.io.FileOutputStream.write(Unknown Source)
		java.io.BufferedOutputStream.flushBuffer(Unknown Source)
		java.io.BufferedOutputStream.flush(Unknown Source)
		java.io.PrintStream.flush(Unknown Source)
		java.io.FilterOutputStream.flush(Unknown Source)
		sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
		sun.nio.cs.StreamEncoder.flush(Unknown Source)
		java.io.OutputStreamWriter.flush(Unknown Source)
		org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.flush(ConsoleReader.java:707)
		org.bukkit.craftbukkit.v1_5_R3.util.TerminalConsoleHandler.flush(TerminalConsoleHandler.java:23)
		java.util.logging.ConsoleHandler.publish(Unknown Source)
		java.util.logging.Logger.log(Unknown Source)
		java.util.logging.Logger.doLog(Unknown Source)
		java.util.logging.Logger.log(Unknown Source)
		net.minecraft.server.v1_5_R3.ConsoleLogManager.info(ConsoleLogManager.java:132)
		net.minecraft.server.v1_5_R3.PendingConnection.a(PendingConnection.java:142)
		org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:244)
		net.minecraft.server.v1_5_R3.PendingConnection.c(PendingConnection.java:55)
		org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:132)
		net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:571)
		net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:280)
		net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:480)
		net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:412)
		net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
------------------------------
현재 스레드: Snooper Timer
	PID: 11 | Suspended: false | Native: false | State: TIMED_WAITING
	Stack:
		java.lang.Object.wait(Native Method)
		java.util.TimerThread.mainLoop(Unknown Source)
		java.util.TimerThread.run(Unknown Source)
------------------------------
현재 스레드: Attach Listener
	PID: 6 | Suspended: false | Native: false | State: RUNNABLE
	Stack:
------------------------------
현재 스레드: Signal Dispatcher
	PID: 5 | Suspended: false | Native: false | State: RUNNABLE
	Stack:

----------- 파일의 끝 -----------

**Comment by EntryPointKR** [comment]
자동 저장(오토세이브) 플러그인을 빼주세요.
스위프트버킷은 자동 저장 기능이 기본으로 내장되어 있습니다.
